1. SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE)
FROM ANIMAL_INS GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE ASC;

2. SELECT NAME, COUNT(NAME) FROM ANIMAL_INS GROUP BY NAME HAVING COUNT(NAME) >= 2 ORDER BY NAME ASC;

3. SELECT HOUR(DATETIME) AS HOUR,COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS WHERE HOUR(DATETIME)>8 AND HOUR(DATETIME)<20
GROUP BY HOUR(DATETIME) ORDER BY HOUR(DATETIME);
