-- 없어진 기록 찾기
-- 서브 쿼리 사용
SELECT ANIMAL_ID, NAME 
FROM ANIMAL_OUTS 
WHERE ANIMAL_ID NOT IN
(
    SELECT ANIMAL_ID 
    FROM ANIMAL_INS
)

-- outer join 사용
SELECT B.ANIMAL_ID, B.NAME
FROM 
(
    ANIMAL_INS A RIGHT JOIN ANIMAL_OUTS B 
    ON A.ANIMAL_ID = B.ANIMAL_ID
)
WHERE A.ANIMAL_ID IS NULL
ORDER BY B.ANIMAL_ID